apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
  volumes:
    - name: mongodb-storage
      hostPath:
        path: /data/mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
