apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: popckorn/k8s-node-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: node-app
